import {
  Baby,
  Banknote,
  Bath,
  Beer,
  Bike,
  Book,
  Briefcase,
  Building2,
  Bus,
  Camera,
  Car,
  Cat,
  Coffee,
  Coins,
  CreditCard,
  Cigarette,
  Dog,
  Droplet,
  Dumbbell,
  FileText,
  Film,
  Flame,
  Fuel,
  Gamepad2,
  Gift,
  Glasses,
  GraduationCap,
  HandCoins,
  Headphones,
  HeartPulse,
  Home,
  IceCreamCone,
  Key,
  Landmark,
  Laptop,
  Martini,
  Music,
  Package,
  Palette,
  ParkingCircle,
  PawPrint,
  Percent,
  Pizza,
  Pill,
  Plane,
  PiggyBank,
  Receipt,
  Recycle,
  Scissors,
  School,
  ShieldCheck,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sofa,
  Stamp,
  Stethoscope,
  Sun,
  Tag,
  Ticket,
  Train,
  Trash2,
  TrendingUp,
  Trophy,
  Truck,
  Tv,
  Umbrella,
  Users,
  UtensilsCrossed,
  Wallet,
  Wifi,
  Wine,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react'

// Set fisso di icone per le categorie (stesso principio della palette colori
// fissa: non un picker libero, per mantenere l'interfaccia coerente).
export const CATEGORY_ICONS: { name: string; Icon: LucideIcon }[] = [
  // Cibo e spesa
  { name: 'UtensilsCrossed', Icon: UtensilsCrossed },
  { name: 'ShoppingCart', Icon: ShoppingCart },
  { name: 'ShoppingBag', Icon: ShoppingBag },
  { name: 'Coffee', Icon: Coffee },
  { name: 'Pizza', Icon: Pizza },
  { name: 'IceCreamCone', Icon: IceCreamCone },
  { name: 'Beer', Icon: Beer },
  { name: 'Wine', Icon: Wine },
  { name: 'Martini', Icon: Martini },
  // Casa e utenze
  { name: 'Home', Icon: Home },
  { name: 'Building2', Icon: Building2 },
  { name: 'Zap', Icon: Zap },
  { name: 'Flame', Icon: Flame },
  { name: 'Droplet', Icon: Droplet },
  { name: 'Sun', Icon: Sun },
  { name: 'Wifi', Icon: Wifi },
  { name: 'Trash2', Icon: Trash2 },
  { name: 'Recycle', Icon: Recycle },
  { name: 'Sofa', Icon: Sofa },
  { name: 'Key', Icon: Key },
  // Trasporti
  { name: 'Car', Icon: Car },
  { name: 'Bus', Icon: Bus },
  { name: 'Train', Icon: Train },
  { name: 'Bike', Icon: Bike },
  { name: 'Fuel', Icon: Fuel },
  { name: 'ParkingCircle', Icon: ParkingCircle },
  { name: 'Plane', Icon: Plane },
  { name: 'Truck', Icon: Truck },
  // Salute e benessere
  { name: 'HeartPulse', Icon: HeartPulse },
  { name: 'Pill', Icon: Pill },
  { name: 'Stethoscope', Icon: Stethoscope },
  { name: 'Dumbbell', Icon: Dumbbell },
  { name: 'Glasses', Icon: Glasses },
  { name: 'Bath', Icon: Bath },
  // Svago e tempo libero
  { name: 'Gamepad2', Icon: Gamepad2 },
  { name: 'Film', Icon: Film },
  { name: 'Tv', Icon: Tv },
  { name: 'Music', Icon: Music },
  { name: 'Headphones', Icon: Headphones },
  { name: 'Camera', Icon: Camera },
  { name: 'Ticket', Icon: Ticket },
  { name: 'Trophy', Icon: Trophy },
  { name: 'Palette', Icon: Palette },
  { name: 'Book', Icon: Book },
  { name: 'Laptop', Icon: Laptop },
  // Persone e famiglia
  { name: 'Baby', Icon: Baby },
  { name: 'Users', Icon: Users },
  { name: 'GraduationCap', Icon: GraduationCap },
  { name: 'School', Icon: School },
  { name: 'PawPrint', Icon: PawPrint },
  { name: 'Dog', Icon: Dog },
  { name: 'Cat', Icon: Cat },
  { name: 'Gift', Icon: Gift },
  // Cura personale e vizi
  { name: 'Scissors', Icon: Scissors },
  { name: 'Shirt', Icon: Shirt },
  { name: 'Cigarette', Icon: Cigarette },
  { name: 'Smartphone', Icon: Smartphone },
  // Finanza, tasse, lavoro
  { name: 'Wallet', Icon: Wallet },
  { name: 'PiggyBank', Icon: PiggyBank },
  { name: 'CreditCard', Icon: CreditCard },
  { name: 'Banknote', Icon: Banknote },
  { name: 'Coins', Icon: Coins },
  { name: 'HandCoins', Icon: HandCoins },
  { name: 'TrendingUp', Icon: TrendingUp },
  { name: 'Briefcase', Icon: Briefcase },
  { name: 'Landmark', Icon: Landmark },
  { name: 'Receipt', Icon: Receipt },
  { name: 'FileText', Icon: FileText },
  { name: 'Stamp', Icon: Stamp },
  { name: 'Percent', Icon: Percent },
  { name: 'ShieldCheck', Icon: ShieldCheck },
  { name: 'Umbrella', Icon: Umbrella },
  { name: 'Wrench', Icon: Wrench },
  { name: 'Package', Icon: Package },
]

const ICON_MAP = new Map(CATEGORY_ICONS.map((entry) => [entry.name, entry.Icon]))

// Icona di riserva per categorie senza icona assegnata (es. create prima di
// questa funzionalità, o importate da Excel) o con un nome non riconosciuto.
export function getCategoryIcon(name?: string | null): LucideIcon {
  if (name) {
    const icon = ICON_MAP.get(name)
    if (icon) return icon
  }
  return Tag
}
